name: Build and Publish Storybook to GitHub Pages

on:
    push:
        branches:
            - 'develop'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            # Add Storybook build and deploy to GitHub Pages as a step in the workflow
            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
              with:
                  install_command: npm ci
                  build_command: npm run build-storybook
                  path: storybook-static # default: dist/storybook
                  checkout: false # default: true
